/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package tv.harukaze.ti.admaker.android;

import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.proxy.TiViewProxy;

import android.app.Activity;
import tv.harukaze.ti.admaker.android.AdMakerView;

// This proxy can be created by calling Tiadmakerandroid.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule=TiAdMakerAndroidModule.class)
public class AdMakerViewProxy extends TiViewProxy
{
	private AdMakerView adMakerView;
	
	// Constructor
	public AdMakerViewProxy(TiContext tiContext) {
		super(tiContext);
	}
	
	@Override
	public TiUIView createView(Activity arg0) {
		adMakerView = new AdMakerView(this);
		return adMakerView;
	}

}


