/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package tv.harukaze.ti.admaker.android;

import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.kroll.KrollDict;
import jp.co.nobot.libAdMaker.libAdMaker;

public class AdMakerView extends TiUIView
{	
	libAdMaker adMaker;
	
	// Constructor
	public AdMakerView(final TiViewProxy proxy) {
		super(proxy);
		adMaker = new libAdMaker(proxy.getContext());
		adMaker.siteId = TiAdMakerAndroidModule.SITE_ID;
		adMaker.zoneId = TiAdMakerAndroidModule.ZONE_ID;
		adMaker.setUrl(TiAdMakerAndroidModule.AD_URL);
		adMaker.start();
		setNativeView(adMaker);
	}

	@Override
	public void processProperties(KrollDict d){
			super.processProperties(d);
	}
}